<form enctype="multipart/form-data" action="addArticle.php" method="post">
    <div class="form-group">
        <label for="title">Nom de l'article.</label>
        <input type="text" name="title" class="form-control" id="title" aria-describedby="titre_art" placeholder="Titre">
    </div>

    <label for="pet-select">Choose a pet:</label>

    <div class="form-group">
<select name="pets" id="pet-select">
    <option value="">--Please choose an option--</option>
    <option value="dog">Dog</option>
    <option value="cat">Cat</option>
    <option value="hamster">Hamster</option>
    <option value="parrot">Parrot</option>
    <option value="spider">Spider</option>
    <option value="goldfish">Goldfish</option>
</select>
</div>


    <div class="form-group">
        <label for="content">Création du contenu de votre article.</label>
        <textarea class="form-control" id="content" name="content" rows="3"></textarea>
    </div>

  <label for="file">Choix d'une image.</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="60000" />
        Envoyez ce fichier : <input name="userfile" type="file" />
    <button type="submit" class="btn btn-primary">Publier</button>
</form>
