<div class="col-12-sm col-md-8">
    <div class="card">
            <div class="card-header bg-dark active">Ajout d'un utilisateur.</div>
      <div class="card-body">
            <!-- inclure une div  bouclant les erreurs si il y en a, en rouge.-->
            <div>
            <?php foreach($errors as $error):?>
                <p><?php echo $error ?></p>
            <?php endforeach;?>  
            </div>
            <form action="addUser.php" method="post">
                <div class="form-group">
                  <label for="username">Nom de l'utilisateur.</label>
                  <input type="text" name="username" value="<?=$username?>" class="form-control" id="username" aria-describedby="titre_art" placeholder="Utilisateur">
                </div>
                <div class="form-group">
                  <label for="password">création du mot de passe.</label>
                  <input type="password" name="password" class="form-control" id="password" aria-describedby="titre_art" placeholder="Mot de passe">
                  <input type="password" name="controlPassword" class="form-control" id="controlPassword" aria-describedby="titre_art" placeholder="Retaper votre mot de passe">
                </div>
                <div class="form-group">
                  <label for="email">Entrer votre adresse mail.</label>
                  <input type="email" name="email" value="<?=$email?>" class="form-control" id="email" aria-describedby="titre_art" placeholder="Adresse mail">
                </div>

                <div class="form-check">
                  <label for="avatar">Séléction de l'avatar.</label><br>
                  <label class="form-check-label" for="avatar"><img src="../public/img/avatar/1.jpg"></label>
                  <input class="form-check-input" type="radio" name="avatar" id="option1" value="1" checked>
                  <label class="form-check-label" for="avatar"><img src="../public/img/avatar/2.jpg"></label>
                  <input class="form-check-input" type="radio" name="avatar" id="option2" value="1">
                  <label class="form-check-label" for="avatar"><img src="../public/img/avatar/3.jpg"></label>
                  <input class="form-check-input" type="radio" name="avatar" id="option3" value="3">
                  <label class="form-check-label" for="avatar"><img src="../public/img/avatar/4.jpg"></label>
                  <input class="form-check-input" type="radio" name="avatar" id="option4" value="4">
                </div><br>
                <div class="form-check">
                  <label for="status">Status de l'utilisateur.</label><br>
                  <label class="form-check-label" for="Administrateur">Administrateur</label><br>
                  <input class="form-check-input" type="radio" name="role" id="ROLE_ADMIN" value="ROLE_ADMIN" ><br>
                  <label class="form-check-label" for="Auteur">Auteur</label><br>
                  <input class="form-check-input" type="radio" name="role" id="ROLE_AUTHOR" value="ROLE_AUTHOR" checked><br>
                  
                </div><br>

                  <button type="submit" class="btn btn-primary">Enregistrer</button>
            </form>
      </div>
    </div>
</div>