<div class="col-12-sm col-md-8">
    <div class="card">
            <div class="card-header bg-dark active">Ajout d'un utilisateur.</div>
      <div class="card-body">
            <form action="addUser.php" method="post">
                <div class="form-group">
                  <label for="username">Nom de l'utilisateur.</label>
                  <input type="text" name="username" class="form-control" id="username" aria-describedby="titre_art" placeholder="Utilisateur">
                </div>
                <div class="form-group">
                  <label for="password">création du mot de passe.</label>
                  <input type="password" name="password" class="form-control" id="password" aria-describedby="titre_art" placeholder="Mot de passe">
                  <input type="password" name="controlPassword" class="form-control" id="controlPassword" aria-describedby="titre_art" placeholder="Retaper votre mot de passe">
                </div>
                <div class="form-group">
                  <label for="email">Entrer votre adresse mail.</label>
                  <input type="email" name="email" class="form-control" id="email" aria-describedby="titre_art" placeholder="Adresse mail">
                </div>
                  <button type="submit" class="btn btn-primary">Enregistrer</button>
            </form>
      </div>
    </div>
</div>