<div class="row">
  <?php foreach($errors as $error):?>
      <p><?php echo $error ?></p>
  <?php endforeach;?>  
  </div>
  <form enctype="multipart/form-data" action="addUser.php" method="post">
      <div class="form-group">
        <label for="username">Nom de l'utilisateur.</label>
        <input type="text" name="username" value="<?=$username?>" class="form-control" id="username" aria-describedby="titre_art" placeholder="Utilisateur">
      </div>
      <div class="form-group">
        <label for="password">création du mot de passe.</label>
        <input type="password" name="password" class="form-control" id="password" aria-describedby="titre_art" placeholder="Mot de passe">
        <input type="password" name="controlPassword" class="form-control" id="controlPassword" aria-describedby="titre_art" placeholder="Retaper votre mot de passe">
      </div>
      <div class="form-group">
        <label for="email">Entrer votre adresse mail.</label>
        <input type="email" name="email" value="<?=$email?>" class="form-control" id="email" aria-describedby="titre_art" placeholder="Adresse mail">
      </div>

      <div class="form-check">
        <label for="avatar">Séléction de l'avatar.</label><br>
        <input type="hidden" name="MAX_FILE_SIZE" value="60000" />
        Envoyez ce fichier : <input name="userfile" type="file" />
      <br>
      <div class="form-check">
        <label for="status">Status de l'utilisateur.</label><br>
        <label class="form-check-label" for="Administrateur">Administrateur</label><br>
        <input class="form-check-input" type="radio" name="role" id="ROLE_ADMIN" value="ROLE_ADMIN" ><br>
        <label class="form-check-label" for="Auteur">Auteur</label><br>
        <input class="form-check-input" type="radio" name="role" id="ROLE_AUTHOR" value="ROLE_AUTHOR" checked><br>
        
      </div><br>

        <button type="submit" class="btn btn-primary">Enregistrer</button>
  </form>
</div>