<p class="lead text-right">Bienvenue, <?=$_SESSION['user']['username']?></p>
  <h1>Accueil</h1>
  <div class="row">
    <div class="col-12-sm col-md-4">
        <div class="card">
          <div class="card-header bg-dark">Visualisation rapide</div>
      <div class="card-body">
          <p>Pour voir tout de suite votre site</p>
        <a href="../index.php" class="d-block btn btn-primary" target="_blank">Afficher votre site</a>
      </div>
    </div>
    <div class="card">
          <div class="card-header bg-dark">Actions rapides</div>
      <div class="card-body">
        <a href="#" class="d-block card-link"><i class="far fa-newspaper"></i> Ajouter un article</a>
        <a href="#" class="d-block card-link"><i class="far fa-file"></i> Ajouter une page</a>
        <a href="addUser.php" class="d-block card-link"><i class="fas fa-user-alt"></i> Ajouter un utilisateur</a>
      </div>
    </div>
      </div>
      <div class="col-12-sm col-md-8">
        <div class="card">
          <div class="card-header bg-dark active">Article rapide</div>
      <div class="card-body">
        <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Titre de l'article</label>
    <input type="text" class="form-control" id="titre_art" aria-describedby="titre_art" placeholder="Titre">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Texte de l'article</label>
    <textarea class="form-control" aria-label="corps_text"></textarea>
  </div>
  <div class="form-check">
  <input class="form-check-input" type="radio" name="typePubli" id="Publier" value="option1" checked>
  <label class="form-check-label" for="Publier">Publier</label>
  <input class="form-check-input" type="radio" name="typePubli" id="Brouillon" value="option2">
  <label class="form-check-label" for="Brouillon">Brouillon</label>
</div>
  <button type="submit" class="btn btn-primary">Enregistrer</button>
</form>
      </div>
    </div>
      </div>
    
  </div>
  <div class="row">
    <div class="col-12 col-md-7">
        <ul class="list-group">
          <li class="list-group-item active bg-dark">
            <h5>Liste des derniers articles</h5>
          </li>
          <li class="list-group-item">
              <h6>Article 1</h6>
              <p>début du texte de l'article (...)</p>
              <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
          </li>
          <li class="list-group-item">
            <h6>Article 2</h6>
            <p>début du texte de l'article (...)</p>
              <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
          </li>
          <li class="list-group-item">
            <h6>Article 3</h6>
            <p>début du texte de l'article (...)</p>
              <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
          </li>
          <li class="list-group-item">
            <h6>Article 4</h6>
            <p>début du texte de l'article (...)</p>
              <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
          </li>
        </ul>
        <a href="#">Voir tout les articles</a>
    </div>
    <div class="col-12 col-md-5">
        <ul class="list-group">
          <li class="list-group-item bg-dark active">
            <h5>Liste des derniers commentaires</h5>
          </li>
          <li class="list-group-item">
              <blockquote class="blockquote text-right">
                  <p class="mb-0">Lorem ipsum dolor sit amet, consectetur (...)</p>
                  <footer class="blockquote-footer">De <cite title="Source Title">Jean Bob</cite></footer>
              </blockquote>
          </li>
          <li class="list-group-item">
            <blockquote class="blockquote text-right">
                  <p class="mb-0">Lorem ipsum dolor sit amet, consectetur (...)</p>
                  <footer class="blockquote-footer">De <cite title="Source Title">Jean Karime</cite></footer>
              </blockquote>
          </li>
          <li class="list-group-item">
              <blockquote class="blockquote text-right">
                  <p class="mb-0">Lorem ipsum dolor sit amet, consectetur (...)</p>
                  <footer class="blockquote-footer">De <cite title="Source Title">Jean Fred</cite></footer>
              </blockquote>
          </li>
          <li class="list-group-item">
            <blockquote class="blockquote text-right">
                  <p class="mb-0">Lorem ipsum dolor sit amet, consectetur (...)</p>
                  <footer class="blockquote-footer">De <cite title="Source Title">Jeanne Sabine</cite></footer>
              </blockquote>
          </li>
        </ul>
        <a href="#">Voir tout les commentaires</a>
    </div>
  </div>
</div>