<div class="container">
  <a href="addUser.php" class="btn btn-primary" href="addUser.php" role="button">Ajouter un article.</a>
  <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">id_article</th>
      <th scope="col">Date publication</th>
      <th scope="col">Title</th>
      <th scope="col">Auteur</th>
    </tr>
  </thead>
  <tbody>

  <?php foreach($listArticle as $article):?>
                <tr>
                    <td><?=$article['id_article']?></td>
                    <td><?=$article['published_date']?></td>
                    <td><?=$article['title']?></td>
                    <td><?=$article['username']?></td>
  
                </tr>
            <?php endforeach;?>
  </tbody>
</table>

</div>