<div class="container">
  <h1>Liste des Utilisateurs:</h1>
  <a class="btn btn-primary" href="#" role="button">Ajouter un utilisateur</a>
  <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Avatar</th>
      <th scope="col">Utilisateur</th>
      <th scope="col">email</th>
    </tr>
  </thead>
  <tbody>

  <?php foreach($listUsers as $user):?>
                <tr>
                    <td><img src="../public/img/avatar/<?=$user['avatar']?>.jpg"></td>
                    <td><?=$user['username']?></td>
                    <td><?=$user['email']?></td>
  
                </tr>
            <?php endforeach;?>
  </tbody>
</table>

</div>



