<div class="container">
  <a href="addArticle.php" class="btn btn-primary" href="addArticle.php" role="button">Ajouter un article.</a>
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">id_article</th>
        <th scope="col">Date publication</th>
        <th scope="col">Title</th>
        <th scope="col">Auteur</th>
        <th class="w-25">Visuel</th>
        <th scope="col">Options</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($listArticle as $article):?>
        <tr>
            <td><?=$article['id_article']?></td>
            <td><?=$article['published_date']?></td>
            <td><?=$article['title']?></td>
            <td><?=$article['username']?></td>
            <td scope="col"><img src="../upload/articles/<?=$article['image']?>" class="img-thumbnail"></td>
            <td><a href="updateArticle.php?id_article=<?=$article['id_article']?>"><i class="fas fa-edit"></i></a> <a href="deleteArticle.php?id_article=<?=$article['id_article']?>"><i class="fas fa-trash-alt"></i></a></td>
        </tr>
      <?php endforeach;?>
    </tbody>
  </table>
</div>

  <!-- MODAL -->
<div class="modal fade" id="picture" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Photo de l'article</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="" class="pictureArticle img-fluid">
      </div>
    </div>
  </div>
</div>