<div class="container">
  <a href="addUser.php" class="btn btn-primary" href="addArticle.php" role="button">Ajouter un article.</a>
  <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">id_categorie</th>
      <th scope="col">Titre categorie</th>
    </tr>
  </thead>
  <tbody>

  <?php foreach($listCategorie as $categorie):?>
                <tr>
                    <td><?=$categorie['id_categorie']?></td>
                    <td><?=$categorie['categorie_name']?></td>
                </tr>
            <?php endforeach;?>
  </tbody>
</table>

</div>