<div class="container">
  <a href="addCategorie.php" class="btn btn-primary" href="addArticle.php" role="button">Ajouter une categorie.</a>
  <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">id_categorie</th>
      <th scope="col">Titre categorie</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($listCategorie as $categorie):?>
      <tr>
          <td><?=$categorie['id_categorie']?></td>
          <td><?=$categorie['categorie_name']?></td>
          <td><a href="updateCategorie.php?id_categorie=<?=$categorie['id_categorie']?>"><i class="fas fa-edit"></i></a> <a href="deleteCategorie.php?id_categorie=<?=$categorie['id_categorie']?>"><i class="fas fa-trash-alt"></i></a></td>
      </tr>
    <?php endforeach;?>
  </tbody>
</table>
</div>