<div class="container">
  <a href="addUser.php" class="btn btn-primary" href="addUser.php" role="button">Ajouter un utilisateur</a>
  <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Avatar</th>
      <th scope="col">Utilisateur</th>
      <th scope="col">Email</th>
      <th scope="col">Status</th>
      <th scope="col">Création du compte</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody>

  <?php foreach($listUsers as $user):?>
                <tr>
                    <td><img src="../upload/avatars/<?=$user['avatar']?>"></td>
                    <td><?=$user['username']?></td>
                    <td><?=$user['email']?></td>
                    <td><?=$user['role']?></td>
                    <td>Le : <?=$user['created_date']?></td>
                    <td><a href="updateUser.php?id_user=<?=$user['id_user']?>"><i class="fas fa-edit"></i></a> <a href="deleteUser.php?id_user=<?=$user['id_user']?>" class="delete"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
            <?php endforeach;?>
  </tbody>
</table>

</div>