<div class="container">
  <a href="addUser.php" class="btn btn-primary" href="addUser.php" role="button">Ajouter un utilisateur</a>
  <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Avatar</th>
      <th scope="col">Utilisateur</th>
      <th scope="col">email</th>
      <th scope="col">status</th>
      <th scope="col">Création du compte</th>
    </tr>
  </thead>
  <tbody>

  <?php foreach($listUsers as $user):?>
                <tr>
                    <td><img src="../public/img/avatar/<?=$user['avatar']?>.jpg"></td>
                    <td><?=$user['username']?></td>
                    <td><?=$user['email']?></td>
                    <td><?=$user['role']?></td>
                    <td>Le : <?=$user['created_date']?></td>
  
                </tr>
            <?php endforeach;?>
  </tbody>
</table>

</div>