<div class="test card text-center">
    <div class="card-header"></div>
        <div class="card-body">
        <h5 class="card-title">Bienvenue dans la section Login Administration</h5>

        <form action="login.php" method="post">
                <div class="form-group">
                  <label for="login">Entrer votre adresse mail.</label>
                  <input type="email" name="login" value="<?= $email ?>" class="form-control" id="login" aria-describedby="titre_art" placeholder="Login">
                </div>
                <div class="form-group">
                  <label for="password">Entrer votre mot de passe.</label>
                  <input type="password" name="password" class="form-control" id="password" aria-describedby="titre_art" placeholder="Mot de passe">
                </div>
                  <button type="submit" class="btn btn-primary">Log me in !</button>
        </form>
        </div>
</div>