<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lora&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <title><?=$title?></title>
  </head>
<body>
<div class="test card text-center">
    <div class="card-header"></div>
        <div class="card-body">
        <h5 class="card-title">Bienvenue dans la section Login Administration</h5>
            <div>
            <?php foreach($errors as $error):?>
                <p><?php echo $error ?></p>
            <?php endforeach;?>  
            </div>
        <form action="login.php" method="post">
                <div class="form-group">
                  <label for="login">Entrer votre adresse mail.</label>
                  <input type="email" name="login" value="<?= $email ?>" class="form-control" id="login" aria-describedby="titre_art" placeholder="Login">
                </div>
                <div class="form-group">
                  <label for="password">Entrer votre mot de passe.</label>
                  <input type="password" name="password" class="form-control" id="password" aria-describedby="titre_art" placeholder="Mot de passe">
                </div>
                  <button type="submit" class="btn btn-primary">Log me in !</button>
        </form>
        </div>
</div>
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Mon propre JS vanilla. -->
  <script src="js/main.js"></script>

</body>
</html>
