<form enctype="multipart/form-data" action="updateArticle.php" method="post">
    <div class="form-group">
        <label for="title">Modifier le nom de l'article.</label>
        <input type="text" name="title" class="form-control" id="title" aria-describedby="titre_art" value="<?= $articleName ?>">
    </div>

    <div class="form-group">
        <label for="categorie">Modifier la catégorie de l'article.</label>
        <input type="text" name="categorie" class="form-control" id="categorie" aria-describedby="titre_art" placeholder="categorie">
    </div>

    <div class="form-group">
        <label for="content">Modifier le contenu de votre article.</label>
        <textarea class="form-control" id="content" name="content" rows="3" ><?= $articleContent ?></textarea>
    </div>

  <label for="file">Changer d'avatar.</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="60000" />
        Envoyez ce fichier : <input name="userfile" type="file" />

    <input id="updated" name="updatedArticle" type="hidden" value="<?=$updatedArticle?>">
    <button type="submit" class="btn btn-primary">Mettre à jour l'article.</button>
</form>
